# Generated by Django 4.0.4 on 2022-05-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('referrees', models.IntegerField(default=0)),
                ('overflow', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True, max_length=100, null=True)),
                ('referral_link', models.URLField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
