# Generated by Django 4.0.4 on 2022-05-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=15)),
                ('translated_text', models.CharField(max_length=250)),
                ('lang', models.CharField(max_length=5)),
            ],
        ),
    ]
