# Generated by Django 4.0.4 on 2022-05-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.TextField(default='', max_length=300),
        ),
    ]
