# Generated by Django 4.0.4 on 2022-05-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_user_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='note',
            field=models.CharField(default='', max_length=300),
        ),
    ]
